### ISSUE TITLE
Unable to add MX records

### ISSUE THREAD

**Issue by prosaugat** [BiznetGIO/RESTKnot#147]
![image](https://user-images.githubusercontent.com/46665428/213154106-b569ae08-d4ef-4331-9a02-5fdce6af9dd9.png)

I am unable to add MX records in Knot. Every time when I try to add new MX records it says 'error: (parser failed)'. Please help me to resolve this.

**Comment by azzamsa** [comment]
I think this question is more suitable to be asked in [Support – Knot DNS](https://www.knot-dns.cz/support/)
