### ISSUE TITLE
Send command tidak memberikan error jika datanya salah

### ISSUE THREAD

**Issue by yudhahidayat** [BiznetGIO/RESTKnot#35]
type: A
host: salahdata
address: apa ini

seharusnya ini error karena bukan ipv4 -- di knot tidak terbentuk jika dibaca dengan api zone_read -- tapi saat menembak api, returnnya sukses:

/sendcommand

 	
stdClass Object
(
[count] => 3
[data] => Array
(
[0] => stdClass Object
(
[data] => stdClass Object
(
)

[description] => Array
(
[0] => stdClass Object
(
[zone-begin] => Array
(
[0] => stdClass Object
(
[sendblock] => stdClass Object
(
[cmd] => zone-begin
[zone] => kalambukmun.xyz
)

)

[1] => stdClass Object
(
[receive] => stdClass Object
(
[type] => block
)

)

)

)

)

[result] => 1
[status] => Command Execute
)

[1] => stdClass Object
(
[data] => stdClass Object
(
)

[description] => Array
(
[0] => stdClass Object
(
[zone-set] => Array
(
[0] => stdClass Object
(
[sendblock] => stdClass Object
(
[data] => "apa ini"
[ttl] => 86400
[rtype] => A
[cmd] => zone-set
[zone] => kalambukmun.xyz
[owner] => salahdata
)

)

[1] => stdClass Object
(
[receive] => stdClass Object
(
[type] => block
)

)

)

)

)

[result] => 1
[status] => Command Execute
)

[2] => stdClass Object
(
[data] => stdClass Object
(
)

[description] => Array
(
[0] => stdClass Object
(
[zone-commit] => Array
(
[0] => stdClass Object
(
[sendblock] => stdClass Object
(
[cmd] => zone-commit
[zone] => kalambukmun.xyz
)

)

[1] => stdClass Object
(
[receive] => stdClass Object
(
[type] => block
)

)

)

)

)

[result] => 1
[status] => Command Execute
)

)

[code] => 200
[status] => success
[message] => Operation succeeded
)

**Comment by anak10thn** [comment]
@meongbego tolong d cek yak

**Comment by meongbego** [comment]
on progress

**Comment by meongbego** [comment]
https://github.com/BiznetGIO/RESTKnot/pull/33/commits/746dda5ec9ae19dff65b5b635e81587b326a2160
solved

**Comment by unggulzmalqp** [comment]
Invalid Hostname does not return error, for example:
hostname: -A0c or A0c- or A.-0c or A-.0c

above entry shall return an error because it is invalid hostname

**Comment by meongbego** [comment]
solve latest validation
