### ISSUE TITLE
Character on value of TXT record maybe not escaped correctly

### ISSUE THREAD

**Issue by unggulzmalqp** [BiznetGIO/RESTKnot#37]
Cannot add TXT record for following value:
"
'
"agus
'agus
@`!Aa"Bb#Cc$Dd%Ee&Ff'Gg(Hh)Ii*Jj+Kk,Ll-Mm.Nn/Oo0Pp1Qq2Rr3Ss4Tt5Uu6Vv7Ww8Xx9Yy:Zz;[{<\|=]}>^~?

**Comment by meongbego** [comment]
https://github.com/BiznetGIO/RESTKnot/pull/33/commits/53af78e269a8da977b0a210bb60fdef675e14a90

Solved
