### ISSUE TITLE
Error saat memasukkan value ¼ ke endpoint /content (record type: MX)

### ISSUE THREAD

**Issue by yudhahidayat** [BiznetGIO/RESTKnot#39]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>KeyError: 'default' // Werkzeug Debugger</title>
<link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
type="text/css">

<link rel="shortcut icon"
href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
<script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
<script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
<script type="text/javascript">
var TRACEBACK = 140470742903664,
CONSOLE_MODE = false,
EVALEX = true,
EVALEX_TRUSTED = false,
SECRET = "atWuLJfXD5h7cxQk5VE7";
</script>
</head>
<body style="background-color: #fff">
<div class="debugger">
<h1>builtins.KeyError</h1>
<div class="detail">
<p class="errormsg">KeyError: 'default'</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">

<ul><li><div class="frame" id="frame-140470755761176">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1997</em>,
in <code class="function">__call__</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>error = None</pre>
<pre class="line before"><span class="ws"> </span>ctx.auto_pop(error)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>def __call__(self, environ, start_response):</pre>
<pre class="line before"><span class="ws"> </span>&quot;&quot;&quot;Shortcut for :attr:`wsgi_app`.&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws"> </span>return self.wsgi_app(environ, start_response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def __repr__(self):</pre>
<pre class="line after"><span class="ws"> </span>return '&lt;%s %r&gt;' % (</pre>
<pre class="line after"><span class="ws"> </span>self.__class__.__name__,</pre>
<pre class="line after"><span class="ws"> </span>self.name,</pre></div>
</div>

<li><div class="frame" id="frame-140470755761792">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1985</em>,
in <code class="function">wsgi_app</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws"> </span>except Exception as e:</pre>
<pre class="line before"><span class="ws"> </span>error = e</pre>
<pre class="line current"><span class="ws"> </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws"> </span>except:</pre>
<pre class="line after"><span class="ws"> </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws"> </span>raise</pre>
<pre class="line after"><span class="ws"> </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws"> </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-140470755758208">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py"</cite>,
line <em class="line">273</em>,
in <code class="function">error_router</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>if self._has_fr_route():</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>return self.handle_error(e)</pre>
<pre class="line before"><span class="ws"> </span>except Exception:</pre>
<pre class="line before"><span class="ws"> </span>pass # Fall through to original handler</pre>
<pre class="line current"><span class="ws"> </span>return original_handler(e)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def handle_error(self, e):</pre>
<pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Error handler for the API transforms a raised exception into a Flask</pre>
<pre class="line after"><span class="ws"> </span>response, with the appropriate HTTP status code and body.</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140470755761568">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_cors/extension.py"</cite>,
line <em class="line">161</em>,
in <code class="function">wrapped_function</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span># Wrap exception handlers with cross_origin</pre>
<pre class="line before"><span class="ws"> </span># These error handlers will still respect the behavior of the route</pre>
<pre class="line before"><span class="ws"> </span>if options.get('intercept_exceptions', True):</pre>
<pre class="line before"><span class="ws"> </span>def _after_request_decorator(f):</pre>
<pre class="line before"><span class="ws"> </span>def wrapped_function(*args, **kwargs):</pre>
<pre class="line current"><span class="ws"> </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
<pre class="line after"><span class="ws"> </span>return wrapped_function</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>if hasattr(app, 'handle_exception'):</pre>
<pre class="line after"><span class="ws"> </span>app.handle_exception = _after_request_decorator(</pre>
<pre class="line after"><span class="ws"> </span>app.handle_exception)</pre></div>
</div>

<li><div class="frame" id="frame-140470755761960">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1540</em>,
in <code class="function">handle_exception</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span># if we want to repropagate the exception, we can attempt to</pre>
<pre class="line before"><span class="ws"> </span># raise it with the whole traceback in case we can do that</pre>
<pre class="line before"><span class="ws"> </span># (the function was actually called from the except part)</pre>
<pre class="line before"><span class="ws"> </span># otherwise, we just raise the error again</pre>
<pre class="line before"><span class="ws"> </span>if exc_value is e:</pre>
<pre class="line current"><span class="ws"> </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws"> </span>else:</pre>
<pre class="line after"><span class="ws"> </span>raise e</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>self.log_exception((exc_type, exc_value, tb))</pre>
<pre class="line after"><span class="ws"> </span>if handler is None:</pre></div>
</div>

<li><div class="frame" id="frame-140470755762016">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/_compat.py"</cite>,
line <em class="line">32</em>,
in <code class="function">reraise</code></h4>
<div class="source"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>from io import StringIO</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>def reraise(tp, value, tb=None):</pre>
<pre class="line before"><span class="ws"> </span>if value.__traceback__ is not tb:</pre>
<pre class="line current"><span class="ws"> </span>raise value.with_traceback(tb)</pre>
<pre class="line after"><span class="ws"> </span>raise value</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>implements_to_string = _identity</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>else:</pre></div>
</div>

<li><div class="frame" id="frame-140470745154168">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1982</em>,
in <code class="function">wsgi_app</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws"> </span>ctx.push()</pre>
<pre class="line before"><span class="ws"> </span>error = None</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line current"><span class="ws"> </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws"> </span>except Exception as e:</pre>
<pre class="line after"><span class="ws"> </span>error = e</pre>
<pre class="line after"><span class="ws"> </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws"> </span>except:</pre>
<pre class="line after"><span class="ws"> </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-140470745154952">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1614</em>,
in <code class="function">full_dispatch_request</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws"> </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws"> </span>if rv is None:</pre>
<pre class="line before"><span class="ws"> </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws"> </span>except Exception as e:</pre>
<pre class="line current"><span class="ws"> </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws"> </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def finalize_request(self, rv, from_error_handler=False):</pre>
<pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Given the return value from a view function this finalizes</pre>
<pre class="line after"><span class="ws"> </span>the request by converting it into a response and invoking the</pre></div>
</div>

<li><div class="frame" id="frame-140470745155568">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py"</cite>,
line <em class="line">273</em>,
in <code class="function">error_router</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>if self._has_fr_route():</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>return self.handle_error(e)</pre>
<pre class="line before"><span class="ws"> </span>except Exception:</pre>
<pre class="line before"><span class="ws"> </span>pass # Fall through to original handler</pre>
<pre class="line current"><span class="ws"> </span>return original_handler(e)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def handle_error(self, e):</pre>
<pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Error handler for the API transforms a raised exception into a Flask</pre>
<pre class="line after"><span class="ws"> </span>response, with the appropriate HTTP status code and body.</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140470745156352">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_cors/extension.py"</cite>,
line <em class="line">161</em>,
in <code class="function">wrapped_function</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span># Wrap exception handlers with cross_origin</pre>
<pre class="line before"><span class="ws"> </span># These error handlers will still respect the behavior of the route</pre>
<pre class="line before"><span class="ws"> </span>if options.get('intercept_exceptions', True):</pre>
<pre class="line before"><span class="ws"> </span>def _after_request_decorator(f):</pre>
<pre class="line before"><span class="ws"> </span>def wrapped_function(*args, **kwargs):</pre>
<pre class="line current"><span class="ws"> </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
<pre class="line after"><span class="ws"> </span>return wrapped_function</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>if hasattr(app, 'handle_exception'):</pre>
<pre class="line after"><span class="ws"> </span>app.handle_exception = _after_request_decorator(</pre>
<pre class="line after"><span class="ws"> </span>app.handle_exception)</pre></div>
</div>

<li><div class="frame" id="frame-140470745156520">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1517</em>,
in <code class="function">handle_user_exception</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>return self.handle_http_exception(e)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>handler = self._find_error_handler(e)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>if handler is None:</pre>
<pre class="line current"><span class="ws"> </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws"> </span>return handler(e)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def handle_exception(self, e):</pre>
<pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Default exception handling that kicks in when an exception</pre>
<pre class="line after"><span class="ws"> </span>occurs that is not caught. In debug mode the exception will</pre></div>
</div>

<li><div class="frame" id="frame-140470745153720">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/_compat.py"</cite>,
line <em class="line">32</em>,
in <code class="function">reraise</code></h4>
<div class="source"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>from io import StringIO</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>def reraise(tp, value, tb=None):</pre>
<pre class="line before"><span class="ws"> </span>if value.__traceback__ is not tb:</pre>
<pre class="line current"><span class="ws"> </span>raise value.with_traceback(tb)</pre>
<pre class="line after"><span class="ws"> </span>raise value</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>implements_to_string = _identity</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>else:</pre></div>
</div>

<li><div class="frame" id="frame-140470745154504">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1612</em>,
in <code class="function">full_dispatch_request</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>self.try_trigger_before_first_request_functions()</pre>
<pre class="line before"><span class="ws"> </span>try:</pre>
<pre class="line before"><span class="ws"> </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws"> </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws"> </span>if rv is None:</pre>
<pre class="line current"><span class="ws"> </span>rv = self.dispatch_request()</pre>
<pre class="line after"><span class="ws"> </span>except Exception as e:</pre>
<pre class="line after"><span class="ws"> </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws"> </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def finalize_request(self, rv, from_error_handler=False):</pre></div>
</div>

<li><div class="frame" id="frame-140470745154224">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py"</cite>,
line <em class="line">1598</em>,
in <code class="function">dispatch_request</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span># request came with the OPTIONS method, reply automatically</pre>
<pre class="line before"><span class="ws"> </span>if getattr(rule, 'provide_automatic_options', False) \</pre>
<pre class="line before"><span class="ws"> </span>and req.method == 'OPTIONS':</pre>
<pre class="line before"><span class="ws"> </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws"> </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line current"><span class="ws"> </span>return self.view_functions[rule.endpoint](**req.view_args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>def full_dispatch_request(self):</pre>
<pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws"> </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws"> </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-140470745157136">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py"</cite>,
line <em class="line">480</em>,
in <code class="function">wrapper</code></h4>
<div class="source"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>:param resource: The resource as a flask view function</pre>
<pre class="line before"><span class="ws"> </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws"> </span>@wraps(resource)</pre>
<pre class="line before"><span class="ws"> </span>def wrapper(*args, **kwargs):</pre>
<pre class="line current"><span class="ws"> </span>resp = resource(*args, **kwargs)</pre>
<pre class="line after"><span class="ws"> </span>if isinstance(resp, ResponseBase): # There may be a better way to test</pre>
<pre class="line after"><span class="ws"> </span>return resp</pre>
<pre class="line after"><span class="ws"> </span>data, code, headers = unpack(resp)</pre>
<pre class="line after"><span class="ws"> </span>return self.make_response(data, code, headers=headers)</pre>
<pre class="line after"><span class="ws"> </span>return wrapper</pre></div>
</div>

<li><div class="frame" id="frame-140470749394256">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/views.py"</cite>,
line <em class="line">84</em>,
in <code class="function">view</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>The arguments passed to :meth:`as_view` are forwarded to the</pre>
<pre class="line before"><span class="ws"> </span>constructor of the class.</pre>
<pre class="line before"><span class="ws"> </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws"> </span>def view(*args, **kwargs):</pre>
<pre class="line before"><span class="ws"> </span>self = view.view_class(*class_args, **class_kwargs)</pre>
<pre class="line current"><span class="ws"> </span>return self.dispatch_request(*args, **kwargs)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>if cls.decorators:</pre>
<pre class="line after"><span class="ws"> </span>view.__name__ = name</pre>
<pre class="line after"><span class="ws"> </span>view.__module__ = cls.__module__</pre>
<pre class="line after"><span class="ws"> </span>for decorator in cls.decorators:</pre></div>
</div>

<li><div class="frame" id="frame-140470749395488">
<h4>File <cite class="filename">"/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py"</cite>,
line <em class="line">595</em>,
in <code class="function">dispatch_request</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>decorators = self.method_decorators</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"> </span>for decorator in decorators:</pre>
<pre class="line before"><span class="ws"> </span>meth = decorator(meth)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws"> </span>resp = meth(*args, **kwargs)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>if isinstance(resp, ResponseBase): # There may be a better way to test</pre>
<pre class="line after"><span class="ws"> </span>return resp</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"> </span>representations = self.representations or OrderedDict()</pre></div>
</div>

<li><div class="frame" id="frame-140470749394984">
<h4>File <cite class="filename">"/home/centos/RESTKnot/api/app/middlewares/auth.py"</cite>,
line <em class="line">40</em>,
in <code class="function">decorated_function</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>access_token = request.headers['Access-Token']</pre>
<pre class="line before"><span class="ws"> </span>stored_data = redis_store.get('{}'.format(access_token))</pre>
<pre class="line before"><span class="ws"> </span>if not stored_data:</pre>
<pre class="line before"><span class="ws"> </span>return response(400, message=&quot; Invalid access token &quot;)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws"> </span>return f(*args, **kwargs)</pre>
<pre class="line after"><span class="ws"> </span>return decorated_function</pre></div>
</div>

<li><div class="frame" id="frame-140470749394368">
<h4>File <cite class="filename">"/home/centos/RESTKnot/api/app/controllers/api/content.py"</cite>,
line <em class="line">37</em>,
in <code class="function">post</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>@login_required</pre>
<pre class="line before"><span class="ws"> </span>def post(self):</pre>
<pre class="line before"><span class="ws"> </span>json_req = request.get_json(force=True)</pre>
<pre class="line before"><span class="ws"> </span>command = utils.get_command(request.path)</pre>
<pre class="line before"><span class="ws"> </span>command = &quot;zn_&quot;+command</pre>
<pre class="line current"><span class="ws"> </span>init_data = cmd.parser(json_req, command)</pre>
<pre class="line after"><span class="ws"> </span>respons = dict()</pre>
<pre class="line after"><span class="ws"> </span>if init_data['action'] == 'insert':</pre>
<pre class="line after"><span class="ws"> </span>table = init_data['data'][0]['table']</pre>
<pre class="line after"><span class="ws"> </span>fields = init_data['data'][0]['fields']</pre>
<pre class="line after"><span class="ws"> </span>ct_rep = fields['nm_content']</pre></div>
</div>

<li><div class="frame" id="frame-140470749393920">
<h4>File <cite class="filename">"/home/centos/RESTKnot/api/app/helpers/cmd_parser.py"</cite>,
line <em class="line">29</em>,
in <code class="function">parser</code></h4>
<div class="source"><pre class="line before"><span class="ws"> </span>except Exception:</pre>
<pre class="line before"><span class="ws"> </span>variabel_check = None</pre>
<pre class="line before"><span class="ws"> </span>if variabel_check:</pre>
<pre class="line before"><span class="ws"> </span>data_variabel[variabel_key] = json[i][parameters_key][variabel_key]</pre>
<pre class="line before"><span class="ws"> </span>else:</pre>
<pre class="line current"><span class="ws"> </span>data_variabel[variabel_key] = endpoint[i][parameters_key][variabel_key]['default']</pre>
<pre class="line after"><span class="ws"> </span>tagfields[parameters_key]=data_variabel</pre>
<pre class="line after"><span class="ws"> </span>parameter=dict()</pre>
<pre class="line after"><span class="ws"> </span>for key in tagfields:</pre>
<pre class="line after"><span class="ws"> </span>try:</pre>
<pre class="line after"><span class="ws"> </span>fields_check = tagfields[&quot;fields&quot;]</pre></div>
</div>
</ul>
<blockquote>KeyError: 'default'</blockquote>
</div>

<div class="plain">
<form action="/?__debugger__=yes&amp;cmd=paste" method="post">
<p>
<input type="hidden" name="language" value="pytb">
This is the Copy/Paste friendly version of the traceback. <span
class="pastemessage">You can also paste this traceback into
a <a href="https://gist.github.com/">gist</a>:
<input type="submit" value="create paste"></span>
</p>
<textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1997, in __call__
return self.wsgi_app(environ, start_response)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1985, in wsgi_app
response = self.handle_exception(e)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py&quot;, line 273, in error_router
return original_handler(e)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_cors/extension.py&quot;, line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/_compat.py&quot;, line 32, in reraise
raise value.with_traceback(tb)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1982, in wsgi_app
response = self.full_dispatch_request()
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py&quot;, line 273, in error_router
return original_handler(e)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_cors/extension.py&quot;, line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/_compat.py&quot;, line 32, in reraise
raise value.with_traceback(tb)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1612, in full_dispatch_request
rv = self.dispatch_request()
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/app.py&quot;, line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py&quot;, line 480, in wrapper
resp = resource(*args, **kwargs)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask/views.py&quot;, line 84, in view
return self.dispatch_request(*args, **kwargs)
File &quot;/home/centos/RESTKnot/API/env/lib/python3.6/site-packages/flask_restful/__init__.py&quot;, line 595, in dispatch_request
resp = meth(*args, **kwargs)
File &quot;/home/centos/RESTKnot/api/app/middlewares/auth.py&quot;, line 40, in decorated_function
return f(*args, **kwargs)
File &quot;/home/centos/RESTKnot/api/app/controllers/api/content.py&quot;, line 37, in post
init_data = cmd.parser(json_req, command)
File &quot;/home/centos/RESTKnot/api/app/helpers/cmd_parser.py&quot;, line 29, in parser
data_variabel[variabel_key] = endpoint[i][parameters_key][variabel_key]['default']
KeyError: 'default'</textarea>
</form>
</div>
<div class="explanation">
The debugger caught an exception in your WSGI application. You can now
look at the traceback which led to the error. <span class="nojavascript">
If you enable JavaScript you can also use additional features such as code
execution (if the evalex feature is enabled), automatic pasting of the
exceptions and much more.</span>
</div>
<div class="footer">
Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
friendly Werkzeug powered traceback interpreter.
</div>
</div>

<div class="pin-prompt">
<div class="inner">
<h3>Console Locked</h3>
<p>
The console is locked and needs to be unlocked by entering the PIN.
You can find the PIN printed out on the standard output of your
shell that runs the server.
<form>
<p>PIN:
<input type=text name=pin size=14>
<input type=submit name=btn value="Confirm Pin">
</form>
</div>
</div>
</body>
</html>

**Comment by meongbego** [comment]
https://github.com/BiznetGIO/RESTKnot/pull/33/commits/794bb009b547dbf7fcd6355ea12c5457c0f26959
